[package]
name = "static_viewer"
version = "0.1.0"
authors = ["Jess Bees <jesse@toomanybees.com>"]
publish = false

[dependencies]
# piston_window = "0.75"
minifb = "0.10"
lib-samus = { path = "../lib-samus" }
proc-samus = { path = "../proc-samus" }
